# Generated by Django 4.0.1 on 2022-09-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawel_pedryc_developer', '0002_essaycls_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='essaycls',
            name='language',
            field=models.CharField(default='Python', max_length=200),
            preserve_default=False,
        ),
    ]
