# Generated by Django 4.0.1 on 2022-09-09 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pawel_pedryc_developer', '0003_essaycls_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prog_lang_category', models.CharField(max_length=200)),
                ('prog_lang_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='essaycls',
            name='language',
        ),
        migrations.AddField(
            model_name='essaycls',
            name='prog_lang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pawel_pedryc_developer.proglang'),
        ),
    ]
