# Generated by Django 4.0.1 on 2022-09-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawel_pedryc_developer', '0004_proglang_remove_essaycls_language_essaycls_prog_lang'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendMeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='essaycls',
            name='guest',
            field=models.ManyToManyField(blank=True, to='pawel_pedryc_developer.SendMeMessage'),
        ),
    ]
