# Generated by Django 4.0.1 on 2022-09-09 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawel_pedryc_developer', '0008_remove_essaycls_organizer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='essaycls',
            name='organizer_email',
            field=models.EmailField(default='2022-09-09', max_length=254),
            preserve_default=False,
        ),
    ]
