# Generated by Django 4.0.1 on 2022-09-09 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawel_pedryc_developer', '0011_essaycls_organizer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essaycls',
            name='date',
        ),
        migrations.RemoveField(
            model_name='essaycls',
            name='organizer_email',
        ),
        migrations.AddField(
            model_name='essaycls',
            name='date_essay',
            field=models.DateField(default='2022-09-09'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='essaycls',
            name='organizer_email_essay',
            field=models.EmailField(default='test@test.com', max_length=254),
            preserve_default=False,
        ),
    ]
