# Generated by Django 4.0.1 on 2022-09-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawel_pedryc_developer', '0013_remove_essaycls_date_essay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='essaycls',
            name='details',
            field=models.TextField(default='Teść mojego rtykułu do podmienienia w panelu administratora'),
            preserve_default=False,
        ),
    ]
