# Generated by Django 4.1.1 on 2022-10-21 10:19

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pawel_pedryc_developer', '0014_essaycls_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_item', embed_video.fields.EmbedVideoField()),
            ],
        ),
        migrations.AddField(
            model_name='essaycls',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pawel_pedryc_developer.videoitem'),
        ),
    ]
