# Generated by Django 4.1.1 on 2023-02-12 22:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pawel_pedryc_developer', '0015_videoobject_essaycls_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date', models.DateField(null=True)),
            ],
            options={
                'verbose_name_plural': 'My Email',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['caption'],
            },
        ),
        migrations.AlterModelOptions(
            name='essaycls',
            options={'verbose_name': 'My Essay'},
        ),
        migrations.AlterModelOptions(
            name='sendmemessage',
            options={'verbose_name': 'ppl newsletter commit'},
        ),
        migrations.AlterField(
            model_name='essaycls',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='essaycls',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_obj', to='pawel_pedryc_developer.videoobject'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=120)),
                ('user_email', models.EmailField(max_length=254)),
                ('text', models.TextField(max_length=23000)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='pawel_pedryc_developer.essaycls')),
            ],
        ),
        migrations.AddField(
            model_name='essaycls',
            name='tags',
            field=models.ManyToManyField(to='pawel_pedryc_developer.tag'),
        ),
    ]
