# Generated by Django 4.1.1 on 2022-10-11 12:58

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pawel_pedryc_developer', '0015_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.AlterModelOptions(
            name='essaycls',
            options={'ordering': ['-added_video']},
        ),
        migrations.AddField(
            model_name='essaycls',
            name='added_video',
            field=models.DateTimeField(auto_now_add=True, default='2022-10-11'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='essaycls',
            name='title_video',
            field=models.CharField(default='No vido, sorry.', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='essaycls',
            name='url_video',
            field=embed_video.fields.EmbedVideoField(default=''),
            preserve_default=False,
        ),
    ]
