# Generated by Django 4.1.1 on 2023-02-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawel_pedryc_developer', '0016_myemail_tag_alter_essaycls_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essaycls',
            name='video',
        ),
        migrations.AddField(
            model_name='essaycls',
            name='video',
            field=models.ManyToManyField(blank=True, related_name='video_obj', to='pawel_pedryc_developer.videoobject'),
        ),
    ]
