# Generated by Django 4.1.1 on 2022-10-24 00:24

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pawel_pedryc_developer', '0016_delete_video_alter_essaycls_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_item_url', embed_video.fields.EmbedVideoField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='essaycls',
            options={},
        ),
        migrations.RemoveField(
            model_name='essaycls',
            name='added_video',
        ),
        migrations.RemoveField(
            model_name='essaycls',
            name='title_video',
        ),
        migrations.RemoveField(
            model_name='essaycls',
            name='url_video',
        ),
        migrations.AddField(
            model_name='essaycls',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pawel_pedryc_developer.videoobject'),
        ),
    ]
