# Generated by Django 4.1.1 on 2022-10-24 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pawel_pedryc_developer', '0017_videoobject_alter_essaycls_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essaycls',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pawel_pedryc_developer.videoobject'),
        ),
    ]
