# Generated by Django 4.1.1 on 2023-02-13 03:58

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pawel_pedryc_developer', '0017_remove_essaycls_video_essaycls_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoobject',
            name='video_intro_item_url',
            field=embed_video.fields.EmbedVideoField(default='www.youtube.com'),
            preserve_default=False,
        ),
    ]
