# Generated by Django 4.1.1 on 2023-02-13 04:03

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pawel_pedryc_developer', '0018_videoobject_video_intro_item_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoobject',
            name='video_intro_item_url',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
