# Generated by Django 4.1.1 on 2022-10-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawel_pedryc_developer', '0018_alter_essaycls_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoobject',
            options={'ordering': ['-added_date']},
        ),
        migrations.AddField(
            model_name='videoobject',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='videoobject',
            name='title_video',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
