# Generated by Django 4.1.1 on 2022-10-24 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pawel_pedryc_developer', '0019_alter_videoobject_options_videoobject_added_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoobject',
            options={},
        ),
        migrations.RemoveField(
            model_name='videoobject',
            name='added_date',
        ),
        migrations.RemoveField(
            model_name='videoobject',
            name='title_video',
        ),
    ]
