# Generated by Django 4.1.1 on 2022-12-13 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pawel_pedryc_developer', '0021_alter_essaycls_options_alter_essaycls_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essaycls',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_obj', to='pawel_pedryc_developer.videoobject'),
        ),
    ]
