# Generated by Django 4.1.1 on 2023-02-14 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawel_pedryc_developer', '0021_videoobject_title_video_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoobject',
            name='title_video',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='videoobject',
            name='title_video_intro',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
