# Generated by Django 4.1.1 on 2022-12-13 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pawel_pedryc_developer', '0024_alter_tag_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['caption']},
        ),
    ]
