# Generated by Django 4.1.1 on 2023-01-28 15:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawel_pedryc_developer', '0026_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essaycls',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
