# Generated by Django 4.1.1 on 2023-02-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawel_pedryc_developer', '0028_alter_comment_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date', models.DateField(null=True)),
            ],
            options={
                'verbose_name': 'MyEmail',
            },
        ),
        migrations.AlterModelOptions(
            name='sendmemessage',
            options={'verbose_name': 'ppl newsletter commit'},
        ),
    ]
