# Generated by Django 4.0.1 on 2022-09-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawel_pedryc_developer', '0012_remove_essaycls_date_remove_essaycls_organizer_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essaycls',
            name='date_essay',
        ),
        migrations.RemoveField(
            model_name='essaycls',
            name='organizer_email_essay',
        ),
        migrations.AddField(
            model_name='essaycls',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='essaycls',
            name='organizer_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
